name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Private VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 10.0.2.4
          username: amgad
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ secrets.PUBLIC_VM_IP }}
          proxy_username: amgad
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd Azure-DevOps-proj-/app
            git pull
            docker compose up -d --build
            '